Assignments/22 - DependencyInjection/WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private IWeatherService _weatherService;

        public HomeController(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View(_weatherService.GetWeatherDetails());
        }

        [HttpGet("/details/{cityCode:maxlength(3)}")]
        public ActionResult Details(string cityCode)
        {
            if (cityCode == null)
            {
                return View("NotFound");
            }

            var city = _weatherService.GetWeatherDetails().Where(c => c.CityUniqueCode == cityCode).FirstOrDefault();

            if (city == null)
            {
                return View("NotFound");
            }

            return View(city);
        }
    }
}

Assignments/22 - DependencyInjection/WebApp/ViewComponents/CityViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts.Models;

namespace WebApp.ViewComponents;

public class CityViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(CityWeather weather)
    {
        return View(weather);
    }
}

Assignments/22 - DependencyInjection/WebApp/Views/Home/Details.cshtml
@model CityWeather

<vc:city weather="Model"></vc:city>

Assignments/22 - DependencyInjection/WebApp/Views/Home/Index.cshtml
@model List<CityWeather>

@{
    foreach (var city in Model)
    {
        <vc:city weather="city"></vc:city>
    }
}

Assignments/22 - DependencyInjection/WebApp/Views/Home/NotFound.cshtml
<div class="container-row">
    <h1>City not found</h1>
    <a href="/">Return to main page</a>
</div>

Assignments/22 - DependencyInjection/WebApp/Views/Home/_City.cshtml
@model CityWeather

@{
    string BackgroundColor(int temperature)
    {
        if (temperature < 44)
        {
            return "blue";
        }
        else if (temperature < 74)
        {
            return "green";
        }
        else
        {
            return "orange";
        }
    }
}

<div class="grid @BackgroundColor(Model.TemperatureFahrenheit)">
    <div class="details">
        <span class="name">@Model.CityName</span>
        <span class="time">@Model.DateAndTime.ToString("H:mm tt")</span>
        <a id="details" href="/details/@Model.CityUniqueCode">Details</a>
        <a id="goback" href="/">Go back</a>
    </div>
    <hr />
    <div>
        <span>@Model.TemperatureFahrenheit</span>
        <span class="degree">°F</span>
    </div>
</div>

<script>
    if (location.href.includes("details")) {
        document.querySelectorAll("#details").forEach(i => i.style.display = "none");
    } else {
        document.querySelectorAll("#goback").forEach(i => i.style.display = "none");
    }
</script>

Assignments/22 - DependencyInjection/WebApp/Views/Home/_Layout.cshtml
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Weather</title>
            <link href="~/style.css" rel="stylesheet">
        </head>
        <body>
            @RenderBody()
        </body>
    </html>

Assignments/22 - DependencyInjection/WebApp/Views/Shared/Components/City/Default.cshtml
@model CityWeather

@{
    string BackgroundColor(int temperature)
    {
        if (temperature < 44)
        {
            return "blue";
        }
        else if (temperature < 74)
        {
            return "green";
        }
        else
        {
            return "orange";
        }
    }
}

<div class="grid @BackgroundColor(Model.TemperatureFahrenheit)">
    <div class="details">
        <span class="name">@Model.CityName</span>
        <span class="time">@Model.DateAndTime.ToString("H:mm tt")</span>
        <a id="details" href="/details/@Model.CityUniqueCode">Details</a>
        <a id="goback" href="/">Go back</a>
    </div>
    <hr />
    <div>
        <span>@Model.TemperatureFahrenheit</span>
        <span class="degree">°F</span>
    </div>
</div>

<script>
    if (location.href.includes("details")) {
        document.querySelectorAll("#details").forEach(i => i.style.display = "none");
    } else {
        document.querySelectorAll("#goback").forEach(i => i.style.display = "none");
    }
</script>